### ISSUE TITLE
Compatability with IE9

### ISSUE THREAD

**Issue by Dillie-O** [talos/jquery-svgpan#5] opened 2012-07-25 18:07 UTC
Greetings,

Your library is a life saver! However, I did run into an issue with getting my pan/zoom to work with IE9.

I know there are some issues with IE already, but I did stumble upon this thread in the SVGPan Google Group that seems to address the issue:

http://code.google.com/p/svgpan/issues/detail?id=6

In particular, they mention adding the following code to get things to work with IE9 and other browsers:

if (navigator.userAgent.match(/like Mac OS X/i)) {
        window.addEventListener('gesturechange',handleMouseWheel,false); // iOS gestures (UNTESTED)
    } else if (navigator.userAgent.toLowerCase().indexOf('firefox') >= 0) {
        window.addEventListener('DOMMouseScroll', handleMouseWheel, false); // Firefox
    } else {
        window.addEventListener('mousewheel', handleMouseWheel, false); // Chrome/Safari/Opera/Explorer9
    }

Do you know where I would need to inject this code in order to get things to work with your library? I tried simply putting it in after the svgPan('viewport') command, but it didn't work. In particular, Chrome gave me the following error:

Uncaught ReferenceError: handleMouseWheel is not defined 

Which makes me think I'm simply misplacing something.

Do you have any ideas?

**Comment by talos** [comment] 2012-08-15 01:58
According to that issue, "DOMMouseScroll" is only useful for Firefox.  Right now, on master, it is being used for all non-webkit browsers (including IE9).

I've committed a fix to 76efe3cc3a6add805e1e0659bcaa76e1a13c2576, on develop.  Could you pull down the develop branch, try it out, and let me know how it works?

Thanks!

**Comment by Dillie-O** [comment] 2012-08-15 16:09
This looks to have fixed the issue!  I'm working with a demo that's using D3 and the counties breakdown. You can grab the full HTML of it here: 

https://gist.github.com/3361254 (you'll have to "view raw" to get the code. I think I did something wonky with the gist 8^D)

If you take your updated jquery-svgpan.js file and drop it into the same folder as the HTML file, you'll see that it works great in IE9.

The one thing I'm noticing is that the zoom/pan in IE9 doesn't seem to respect the boundaries of the box, meaning it will zoom in and go beyond the grey box, the panning will go outside of it as well.

It could just be something related to some of the missing city/county data since my example is pulling it all down from the server, but it might be work looking into. Just getting the zoom to work is a huge step for the project I'm on.

Many thanks!

**Comment by mikew0143** [comment] 2012-08-19 11:44
I had the same boundaries issue with IE9 with my own non D3 app and tested with a simple rectangle. Panning seems to be calculating the boundaries incorrectly, it partially works. Dragging the rectangle is only constrained by the window boundaries not the viewport. I haven't applied the fix above so zooming does not work for me in IE9.

Otherwise it is working well under Chrome and FF (in a Wordpress plugin). Thanks!

**Comment by talos** [comment] 2012-08-19 15:03
I've merged 76efe3c into master.

It's fairly involved for me to test IE9 compatibility, so please let me know if you develop a fix for the boundary issue -- I'd be happy to merge it in.  Please issue any pull requests on develop.

**Comment by Dillie-O** [comment] 2012-08-19 16:53
I'll see if I can make things happen since this will be pertaining to my upcoming project, but any insights along the way are greatly appreciated 8^D

**Comment by mikew0143** [comment] 2012-08-23 22:56
It seems that the IE9 boundary issues are just that, IE9. http://stackoverflow.com/questions/5642815/svg-draws-outside-canvas-boundary-in-internet-explorer-9

So adding overflow: hidden to the svg canvas resolves the zoom/pan boundary issue.

**Comment by talos** [comment] 2012-08-24 01:05
Interesting/annoying.  Do you think applying overflow: hidden to the canvas by default be overkill?  Trying to think of regular use cases, none coming to mind.

**Comment by talos** [comment] 2012-08-28 21:31
I've added `overflow:hidden` to the demo to make IE9 happy with 630ce3c4e2c3b251c8197e8963493d6f92058efc.

**Comment by Dillie-O** [comment] 2012-08-28 21:40
Excellent! I'll be pulling down that update here soon to test with some of my local stuff and I'll let you know if anything creeps up.
Thanks for your help with this all!
[:: Sean ::]

Date: Tue, 28 Aug 2012 14:31:34 -0700

**Comment by talos** [comment] 2012-08-28 21:42
That would be excellent, since it's very hard for me to do testing on IE.  I'll reopen the ticket if there are new issues.

**Comment by kenc3dan** [comment] 2013-02-28 23:18
Bad news...
Using those modifications to jquery-svgpan.js provided at https://github.com/talos/jquery-svgpan/commit/76efe3c
I cannot neither pan nor use the mousewheel in demo.html in IE9.
I can confirm that everything still works in FF 18.0.2 and Chrome 24.0.1312.57 m.

**Comment by talos** [comment] 2013-02-28 23:25
@kenc3dan Thanks for the word!  I don't have a way to test IE9, but if you can attempt a patch, test on your end, and pull, I would be very grateful.

**Comment by kenc3dan** [comment] 2013-03-01 16:40
One observation so far, I can't pan/zoom unless I click off of IE9 and then click back into it. I can then pan and zoom, even using the mousewheel, over either of the two SVGs but cannot change focus to the other one without click off IE9 and then clicking back into one of the two. Seems like some sort of focus problem. I'll goof with it a bit.

**Comment by kenc3dan** [comment] 2013-03-01 16:46
Further, I can click off IE9, focus on one SVG, click off IE9 again, focus on the other SVG and now BOTH respond to the scroll wheel simultaneously and BOTH can be panned individually.

**Comment by kenc3dan** [comment] 2013-03-13 17:11
Man, I have just had no luck getting SVGPan (jQuery or otherwise) working with IE9 and FF and Chrome all at the same time. 
I'd be willing to pay for a library that does what I need:
-pan/zoom/mousewheel navigate SVG graphic
-highlight a named SVG element (opacity, stroke, color change)
-"pan+zoom to" named SVG element (animated with easing)

**Comment by kenc3dan** [comment] 2013-03-13 17:54
The problem with IE9 still seems to lie in something to do with focus.
I've tried manually setting focus to a given SVG but this doesn't work. I still have to click out of IE9 and then back in for jQuery SVGPan to work.

**Comment by kenc3dan** [comment] 2013-03-13 19:08
Ok, I've eliminated focus as an issue. It turns out IE9 is not handling mouse events properly. onMouseEnter and onMouseLeave aren't happening so mouseMove isn't being bound/unboound to the root. I'm on it.

**Comment by kenc3dan** [comment] 2013-03-13 19:13
Looks like a jQuery 1.7.2 problem.
http://stackoverflow.com/questions/11435883/mouseenter-mouseleave-events-not-firing-for-svg-elements-using-jquery-on

**Comment by kenc3dan** [comment] 2013-03-13 19:47
Now using jQuery 1.9. 
mouseenter and mouseleave now function properly in IE9 and seemingly everywhere else.
Modified browser detect to use navigator object instead of deprecated jQuery .browser.

**Comment by talos** [comment] 2013-03-14 00:11
@kenc3dan Thanks for all the IE9 testing.  I've merged in your pull request, would you be OK with me closing this issue?

**Comment by kenc3dan** [comment] 2013-03-14 20:28
Sure, no problem, close it up. Thanks for this entire project!

**Closed as completed** 2013-03-14 22:04 UTC

**Comment by johnmphelan** [comment] 2013-04-09 19:56
Hi,

SVGPan is fantastic so thanks to all involved.

Just wondering, did anyone ever add functionality to support ios devices (I'm mainly interested in the i-pad at the moment!)? I've been trying to work with so changes myself but I haven't got past being able to pan more than one svg element e.g. a rect / circle. I can't get it to work with a group of svg elements at once based on the various touch events.

Any help would be greatly appreciated!

Thanks on advance,

John

**Comment by talos** [comment] 2013-04-09 23:01
@johnmphelan Thanks!  SVGPan does not support iOS as-is.  I don't know how difficult/possible it would be to do so, but if you figure something out, a patch would be very much appreciated.

**Comment by johnmphelan** [comment] 2013-04-11 11:32
Hi. This isn't the most beautiful code (I haven't got time to clean it up at the moment!), but this allows the panning functionality to work correctly for a large group of svg elements on the ipad! I've tested it on the i-pad and it's working fine but I haven't craked how to get the zoom working yet - so any help would be greatly appreciated!!!

svg image file contents (i.e. a group of svg rects but any svg elements that can be grouped will work and I also have tested defs sections and they work fine on the ipad too!):

<?xml version="1.0" standalone="no"?>
<svg    
    xmlns="http://www.w3.org/2000/svg" 
    xmlns:xlink="http://www.w3.org/1999/xlink"
    version="1.1">

<script type="text/javascript" xlink:href="SVGPan.js" />
<script type="text/javascript" xlink:href="IOSPan.js" />

<g id="viewport" x="40" y="40" width="800" height="800" transform="translate(40,40)"
    ontouchstart="touchStart(event);" 
    ontouchmove="touchMove(event);"
    ongesturestart="gestureStart(event);"
    ongesturechange="gestureChange(event);">

<rect id="square" width="100%" height="100%" style="fill:red;stroke-width:1;stroke:rgb(0,0,0)" ></rect>
<rect id="square" width="100" height="100" style="fill:#3399CC" x="20" y="20"></rect>
<rect id="square" width="100" height="100" style="fill:#3399CC" x="150" y="150"></rect>
</g>
</svg>

js file contents (SVG pan is the original SVGPan discussed above)

var ix, iy, touchX, touchY, width, height;
var svgRoot = null;
var handlingGesture = false;
var stateTf;

function touchStart(event) {

```
var svgDoc = event.target.ownerDocument;
var g = getRoot(svgDoc);    

event.preventDefault();

if(!handlingGesture) {
    if(event.touches.length == 1) {
        var touch = event.touches[0];

        ix = parseInt(g.getAttributeNS(null, 'x'));
        iy = parseInt(g.getAttributeNS(null, 'y'));

        touchX = touch.pageX;
        touchY = touch.pageY;
    } 
}
```

}

function touchMove(event){
    event.preventDefault();

```
var svgDoc = event.target.ownerDocument;
var g = getRoot(svgDoc);    

if(!handlingGesture) {
    if(event.touches.length == 1) {
        var touch = event.touches[0];
        var dx = touch.pageX - touchX;
        var dy = touch.pageY - touchY;
        var newX = ix + dx;
        var newY = iy + dy;

        g.setAttributeNS(null, 'x', newX);
        g.setAttributeNS(null, 'y', newY);

        var MovedX = parseInt(g.getAttributeNS(null, 'x'));
        var MovedY = parseInt(g.getAttributeNS(null, 'y'));

        g.setAttribute('transform','translate(' + MovedX + ',' + MovedY + ')');
    } 
}
```

}

That's all you need for the panning (as long as you include the SVGPan.js obviously!)

I've been adding to the bottom of the above js file with things like the following but I still haven't cracked how to get the zoom to work!

function touchEnd(event) {
    if(event.touches.length == 0) {
        handlingGesture = false;
    }
}

// This calculates and sets the width and height vars to be used in the gesture change
function gestureStart(event) {

```
//alert("Gesture starting");

event.preventDefault(); 
handlingGesture = true;

// Replace
var node = event.target;

// With
var svgDoc = event.target.ownerDocument;
var g = getRoot(svgDoc);

// With
ix = parseInt(g.getAttributeNS(null, 'x'));
iy = parseInt(g.getAttributeNS(null, 'y'));
//alert("Gesture start. x: " + x + ", y: " + y);

// alert("Gesture start sets vars: width: " + width + ", height: " + height + ", transform: " + transform)

 width = parseInt(g.getAttributeNS(null, 'width'));
 height = parseInt(g.getAttributeNS(null, 'height'));
 // var transform = (g.getAttributeNS(null, 'transform'));
 //alert("Gesture start sets vars: width: " + width + ", height: " + height + ", transform: " + transform)

 //alert("Fini");
 handlingGesture = false;
```

}

function gestureChange(event) {

```
//alert("Gesture changeing");
event.preventDefault();

// With
var svgDoc = event.target.ownerDocument;
var g = getRoot(svgDoc);

// scale
var newWidth = width * event.scale;
var newHeight = height * event.scale;

//alert("width: " + width + ", newWidth: " + newWidth + ", height: " + height + ", newHeight: " + newHeight);
var newX = ix - (newWidth - width)/2;
var newY = iy - (newHeight - height)/2;
// Reduce the size of the scaling...
newX = newX * 0.1;
newY = newY * 0.1;

//alert("x: " + x + ", y: " + y + ", newX: " + newX + ", newY: " + newY);
// g.setAttribute("transform", "scale(" + newX + "," + newY + ")");

g.setAttributeNS(null, 'width', newWidth);
g.setAttributeNS(null, 'height', newHeight);
g.setAttributeNS(null, 'x', newX);
g.setAttributeNS(null, 'y', newY);

var scaley = event.scale;

// var check = parseInt(g.getAttributeNS(null, 'width'));
//alert("About to transform, event scale is: " + scaley);

// When this is caslled it moves back to the original corner points!
g.setAttribute("transform", "scale(" + scaley + "," + scaley + ")");

handlingGesture = false;
```

}

**Comment by psled** [comment] 2013-05-24 00:37
In case you will need multi-touch support at least for Chrome desktop browser (Mac), please check out my fork of this library: https://github.com/pawelsledzikowski/jquery-svgpan
